name: Backend API Deployment to Azure Web App

on:
  push:
    branches: 
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd parkway.api
          npm install
          npm run build:staging

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'staging-pkwy-backend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
